version: '3.9'
services:

  sql:
    image: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=proxy
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpass
      - SERVICE_NAME=sql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysql", "-D", "proxy", "-e", "SELECT * FROM dids LIMIT 1"]
      interval: 3s
      timeout: 2s
      retries: 15

  proxy:
    build:
      context: proxy
    depends_on:
      sql:
        condition: service_healthy
    volumes:
      - ./proxy:/etc/kamailio

